### ISSUE TITLE
Should this just deploy out of the box?

### ISSUE THREAD

**Issue by prestoncrawford** [coresecure/Adobe-AEM-Brightcove-Connector#24]
We're struggling with a situation where the jar seemingly gets installed and the bundle is there, we can see it under /system/console/bundles, but we can't reference it. Instead we're forced to install the bundle manually through /system/console/bundles to get this working on our hosted Linux environments.

**Comment by pablo-kropilnicki** [comment]
Hey Preston, could you please elaborate in detail how you installed the bundle?
Additionally, is the bundle active and working as shown in the system/console/bundles menu with all dependencies active?

Please provide AEM version and Brightcove Connector release version installed.

**Comment by prestoncrawford** [comment]
Installed the bundle via code, so by running the maven build. I work for a customer that has some customizations in the code for things like modifying media query results.

**Comment by pablo-kropilnicki** [comment]
I understand.. is this for AEM 6.2+?

If not for 6.2+, I highly recommend retrying by uploading the release to the crx-pack manager on the AEM interface as highlighted here:  https://support.brightcove.com/adobe-aem-brightcove-connector-installation

All AEM vanilla versions we're supported and tested on multiple operating systems, including linux.

Please include the status of the bundle as requested above? (to eliminate any dependency problems etc)

**Comment by prestoncrawford** [comment]
We have deployed the package through crx and it deploys just fine. That's not the scenario we face. The scenario we face is that these deploys *should* happen via maven because of our changes. We can bundle it up, build a zip and deploy it manually, but we'd like to be able to deploy through maven.

**Comment by pablo-kropilnicki** [comment]
> Installed the bundle via code, so by running the maven build. I work for a customer that has **some customizations in the code** for things like modifying media query results.

> We have deployed the package through crx and it deploys just fine. That's not the scenario we face. The scenario we face is that these deploys _should_ happen via maven **because of our changes**. We can bundle it up, build a zip and deploy it manually, but we'd like to be able to deploy through maven.

The maven autoInstalPackage profile to AEM is working with no problems and is equivalent to the crx/packmanager push of the built bundle as highlighted in the README.md. It seems to me that there is no issue when you install directly the release sources, and that you're facing trouble pushing to your instance with your 'custom' code.

We don't support any customization of the connector, the answer to your question is that yes, the Brightcove connector deploys out of the box. You have specified that you are able to build and deploy manually, therefore your problem is related to the maven push process.

I recommend passing parameter -X into your maven command and debugging the dependencies called by your custom code.

*Tested to work from 5.5.0 source on AEM 6.2 , 6.3 vanilla*
